#!/usr/bin/env bash
# a Bash script that pings an IP address passed as an argument. Requirements:
#+ Accepts a string as an argument
#+ Displays 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}' if no argument passed
#+ Pings the IP 5 times

if [ $# -eq 0 ]; then
  echo "Usage: $0 {IP_ADDRESS}"
else
  ip_address="$1"
  echo "PING $ip_address ($ip_address) 56(84) bytes of data."
  ping_output=$(ping -c 5 "$ip_address")
  echo "$ping_output"
fi
